name: On push
on: [push]
jobs:
  build:
    name: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Get All Changed Files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: building modified images
        run: |
          for changed_file in ${{ steps.changed_files.outputs.all }}; do          
            if [[ $changed_file == *"images"* ]]; then
              echo "processing $IMG_PATH"
              ARCH=linux/amd64
              if [[ $changed_file == *"arm"* ]]; then
                ARCH=linux/arm64
              fi
              IMG_PATH=$(dirname "$changed_file")
              make buildx "IMG_PATH=$IMG_PATH" "ARCH=$ARCH"
            fi
          done
