name: On push
on: [push]
jobs:
  build:
    name: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: building modified images
        run: |
          if [[ $BRANCH == "refresh-all" ]]; then
            make build-push-all-arm
            make build-push-all-intel
            exit 0
          fi
          
          make build-modified-images